Traceback (most recent call last):
  File "/home/wugd/code/workbooks-git/ABSP-sweigart/chapter10.py", line 27, in test_traceback
    raise Exception('Error message')
Exception: Error message
